// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCYlc_lqA4dqXfZIwDOIAxL2t16N4Ub9RY',
    appId: '1:868915889927:web:12054b55ab4808e3e867a2',
    messagingSenderId: '868915889927',
    projectId: 'xdi-course',
    authDomain: 'xdi-course.firebaseapp.com',
    storageBucket: 'xdi-course.firebasestorage.app',
    measurementId: 'G-K37W2E7LHT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBuqpjgYnuqoOW24FrCWlQsXAp3Ak4yvq8',
    appId: '1:868915889927:android:434d8d8bafb41832e867a2',
    messagingSenderId: '868915889927',
    projectId: 'xdi-course',
    storageBucket: 'xdi-course.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDRy4_ORbufW9Pj7OJwDBq9GdVommZUrZ8',
    appId: '1:868915889927:ios:c43029ce59aa49f4e867a2',
    messagingSenderId: '868915889927',
    projectId: 'xdi-course',
    storageBucket: 'xdi-course.firebasestorage.app',
    iosBundleId: 'com.example.flutterNotesApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDRy4_ORbufW9Pj7OJwDBq9GdVommZUrZ8',
    appId: '1:868915889927:ios:c43029ce59aa49f4e867a2',
    messagingSenderId: '868915889927',
    projectId: 'xdi-course',
    storageBucket: 'xdi-course.firebasestorage.app',
    iosBundleId: 'com.example.flutterNotesApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCYlc_lqA4dqXfZIwDOIAxL2t16N4Ub9RY',
    appId: '1:868915889927:web:b06dced58b07da82e867a2',
    messagingSenderId: '868915889927',
    projectId: 'xdi-course',
    authDomain: 'xdi-course.firebaseapp.com',
    storageBucket: 'xdi-course.firebasestorage.app',
    measurementId: 'G-NCLJVNS2QN',
  );
}
